# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Auto update 7za

on:
  push:
    branches:
    - master
  #schedule:
  #  - cron: '5 4 5 */3 *'

jobs:
  update-win:
    name: update 7za on ${{ matrix.arch }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: 
          - windows-latest
        arch: ['x86','x64','arm','arm64']
    steps:
      - uses: actions/checkout@v4
      - name: Download ${{ matrix.arch }} version
        if: ${{ matrix.arch != 'x86' }}
        uses: robinraju/release-downloader@v1.9
        id:   downexe
        with:
          repository: "ip7z/7zip"
          latest: true
          fileName: "7z*-${{ matrix.arch }}.exe"
          extract: false
      - name: Download x86 version
        if: ${{ matrix.arch == 'x86' }}
        uses: robinraju/release-downloader@v1.9
        id:   downexe-x86
        with:
          repository: "ip7z/7zip"
          latest: true
          fileName: "7z*.exe"
          extract: false
      - name: install 7zip on ${{ matrix.os }}
        if: ${{ matrix.arch != 'x86' }}
        run: |
          ${{ fromJson(steps.downexe.outputs.downloaded_files)[0] }}.exe /S /D=".\7-Zip"
      - name: install 7zip on ${{ matrix.os }}
        if: ${{ matrix.arch == 'x86' }}
        run: |
          ${{ fromJson(steps.downexe.outputs.downloaded_files)[2] }}.exe /S /D=".\7-Zip"
          
        
  update-mac:
    name: update 7za on mac
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update
          brew uninstall p7zip
          brew install sevenzip
          cp /usr/local/Cellar/sevenzip/*/bin/7zz mac/${arch}/7z
      - id: commit_files
        name: Commit files  
        run:
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
              git add mac/
              git commit -am "GH Action Files updated $(date) update 7za on mac"
              git push -f origin main
          fi
